title:            annaken
description:      annaken
name:             Anna Kennedy
github_username:  annaken

logo:             
disqus_shortname: annaken

# Assign a default image for your site's header and footer
default_bg:       some-image.jpg
search:           true
share:            true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true

# Turn on or off the fin animations in the header and footer
animated_fins:    false

# Specify the fin color in RGB value
fin_color:        "255,255,255"

# Change url to your domain. Leave localhost server or blank when working locally.
url:              "http://annaken.github.io"


# Owner/author information
owner:
  name:           Anna Kennedy
#  avatar:         your-photo.jpg
#  email:          your@email.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Infrastructure engineer and professional chaos monkey

  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github:
  linkedin:
  instagram:
  tumblr:
  hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship "http://plus.google.com/123123123123132123"
  google_plus:   

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify: m9WsXe8Lv71_3rWe70CKkgQtAGsKn9U3C1vD9jl-99U
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Tags
    url: /tags

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Oslo
future:      true
pygments:    true
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
